### ISSUE TITLE
Business Models

### ISSUE THREAD

**Issue by kaiser70** [FH-Cloud-Computing/website#3]
@janoszen for the business models 
https://github.com/FH-Cloud-Computing/website/blame/master/docs/lectures/1-cloud-intro/index.md#L327 
I would like to add some comment that cloud computing is not only about technology, but very much also dependant on the business aspects associated with the case. 

Many times we hear, "we have done an analysis and concluded the cloud way is more expensive than staying on premise!", however rarely the comparision has done under fair conditions.

**Comment by ghost** [comment]
Agreed, I will add a section about business analysis of return on investment.
