### ISSUE TITLE
PPTX Download

### ISSUE THREAD

**Issue by kaiser70** [FH-Cloud-Computing/website#5]
I suggest to only offer PDF as download format. 
https://github.com/FH-Cloud-Computing/website/blame/master/docs/lectures/1-cloud-intro/index.md#L2

**Comment by ghost** [comment]
Why would you do that? PDFs can't have embedded audio and I intended to add narration to the slides.

**Comment by kaiser70** [comment]
well, basically to protect our content ;) I NEVER EVER give any ppt to customers for instance. In some cases when specificially asked I did. but as a general rule none of my customers got an email with a pptx attached. 
Hmm, while your idea sounds interesting, isn't this already too much? At least for our first shot ;)

**Comment by ghost** [comment]
Well the "video version" will be the PPTX played on video with the narration. PPTX has the advantage of being able to jump between slides.

As for protecting our content... the text is more valuable and is up on the Internet. As the saying goes copying is a form of flattery and I would hope that our content is so good that other teachers start using it. This is different from a corporate setting I would think.

**Comment by ghost** [comment]
@kaiser70 can we close this issue? I think we discussed it in great detail. :)
