### ISSUE TITLE
Grading: Github uploads

### ISSUE THREAD

**Issue by kaiser70** [FH-Cloud-Computing/website#6]
you state "close to working" in https://github.com/FH-Cloud-Computing/website/blame/master/docs/grading/index.md#L11
what would that exactly mean?

**Comment by ghost** [comment]
I don't exactly know yet. I would like to not fail students who just have some simple bugs.

**Comment by ghost** [comment]
Related to #8

**Comment by ghost** [comment]
As agreed we will remove the "github" requirement and split the grades into 2 instead of 3 parts. One part is the minimum requirement, the other part is the "bonus" automation target.
