### ISSUE TITLE
Glossary

### ISSUE THREAD

**Issue by kaiser70** [FH-Cloud-Computing/website#7]
By comming across https://github.com/FH-Cloud-Computing/website/blame/master/docs/lectures/1-cloud-intro/index.md#L218 I was wondering if a Glossary would be needed. 
Something like: https://www.evolveip.net/support/cloud-computing-definition

**Comment by ghost** [comment]
We can do that, and also collect the "In a hurry?" notes in a single place. I would refrain from asking too many definitions in the tests though.
